package cookie.server.enums;

public enum EffectType {
    HARVEST_YIELD,
    BAKE_OUTPUT,
    MARKET_FEE_REDUCTION,
    WAGE_INTEREST_REDUCTION,
    RESOURCE_WAGE_REDUCTION,
    STORAGE_CAP_BONUS,
    BUILDING_BUFFER_BONUS
}
