version: "3.8"
services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: CookieData
    ports:
      - 5460:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s       # Zeit zwischen den Checks
      timeout: 5s         # Timeout für jeden Check
      retries: 5          # Anzahl der Wiederholungen vor Fehlerstatus

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: CookieData
    volumes:
      - cert:etc/letsencrypt/r3dconcrete.de/

volumes:
  db_data:
  cert:

