openapi: "3.0.3"
info:
  title: API Title
  version: "0.0.1"
servers:
  - url: http://localhost:3000/v1

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: string
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: string

  /users/{userId}:
    get:
      summary: Returns a user.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 4
        cookies:
          type: number
          example: 1.0
        sugar:
          type: number
          example: 1.0
        flour:
          type: number
          example: 1.0
        eggs:
          type: number
          example: 1.0
        butter:
          type: number
          example: 1.0
        chocolate:
          type: number
          example: 1.0
        milk:
          type: number
          example: 1.0
      required:
        - id
        - cookies
        - sugar
        - flour
        - eggs
        - butter
        - chocolate
        - milk
